name: CI - Etudiant Service

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build du projet
        run: mvn clean install -DskipTests

      - name: 🧪 Exécuter les tests
        run: mvn test

      - name: 🎯 Vérification SonarQube
        run: mvn sonar:sonar -Dsonar.projectKey=missmari-dot_etudiantgestion -Dsonar.organization=missmari-dot-Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 🏷 Création d’une image Docker
        run: |
          docker build -t etudiantgestion:latest .

      - name: 🔑 Login à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🚀 Push de l'image Docker (Docker Hub)
        run: |
          docker tag gateway-service:latest mariama640/etudiantgestion:latest
          docker push mariama640/etudiantgestion:latest