apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    domain = grafana.example.com
    root_url = %(protocol)s://%(domain)s/
    serve_from_sub_path = true

    [security]
    admin_user = admin
    admin_password = admin

    [auth.anonymous]
    enabled = true

  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring:9090
        isDefault: true

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: Default
        orgId: 1
        folder: ''
        type: file
        options:
          path: /var/lib/grafana/dashboards

  dashboard-provisioning.yaml: |
    apiVersion: 1
    dashboards:
      - name: Kubernetes Monitoring
        type: file
        options:
          path: /var/lib/grafana/dashboards/k8s-dashboard.json
