apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  type: NodePort    # Ou NodePort si tu n'as pas de LB
  ports:
    - port: 9098
      targetPort: 9098
      protocol: TCP
  selector:
    app: prometheus
