apiVersion: v1
kind: Service
metadata:
  name: etudiantgestion
  namespace: preprod
spec:
  selector:
    app: etudiantgestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: NodePort
  